-- ============================================================================
-- TEAM CONTRIBUTION MANAGEMENT SYSTEM - DATABASE SCHEMA SCRIPT (init.sql)
-- Complete DDL: Extensions, Table Creations, Schema Upgrades (Alter), & Indexes
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1. TABLE CREATIONS (CREATE TABLE IF NOT EXISTS)
-- ============================================================================

-- 1. Roles Table
CREATE TABLE IF NOT EXISTS roles (
    role_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    role_name VARCHAR(100) NOT NULL UNIQUE,
    default_contribution_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 2. Event Types Table
CREATE TABLE IF NOT EXISTS event_types (
    event_type_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_type_name VARCHAR(100) NOT NULL UNIQUE,
    base_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    has_tenure_rule BOOLEAN NOT NULL DEFAULT FALSE,
    tenure_threshold_years NUMERIC(4,2) NOT NULL DEFAULT 1.0,
    new_entrant_share_percentage NUMERIC(5,2) NOT NULL DEFAULT 50.0,
    standard_share_percentage NUMERIC(5,2) NOT NULL DEFAULT 100.0,
    rule_description VARCHAR(200) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 3. Users Table
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(500) NOT NULL,
    role VARCHAR(20) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    profile_image VARCHAR(500) NULL,
    password_reset_otp VARCHAR(10) NULL,
    password_reset_otp_expiry TIMESTAMPTZ NULL,
    is_two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 4. User MFA Devices Table
CREATE TABLE IF NOT EXISTS user_mfa_devices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    device_label VARCHAR(100) NOT NULL,
    secret_key VARCHAR(100) NOT NULL,
    date_added TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 5. Device Details Table
CREATE TABLE IF NOT EXISTS device_details (
    device_detail_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    device_id VARCHAR(255) NOT NULL,
    device_name VARCHAR(100) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(100) NOT NULL,
    os VARCHAR(50) NOT NULL,
    os_version VARCHAR(50) NOT NULL,
    system_name VARCHAR(50) NOT NULL,
    system_version VARCHAR(50) NOT NULL,
    device_type SMALLINT NOT NULL DEFAULT 1,
    app_version VARCHAR(20) NOT NULL,
    total_memory BIGINT NULL,
    browser VARCHAR(100) NOT NULL,
    browser_version VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 6. Device Login History Table
CREATE TABLE IF NOT EXISTS device_login_history (
    history_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    device_detail_id UUID NOT NULL REFERENCES device_details(device_detail_id) ON DELETE CASCADE,
    login_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    logout_time TIMESTAMPTZ NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 7. Members Table
CREATE TABLE IF NOT EXISTS members (
    member_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    role_id UUID NOT NULL REFERENCES roles(role_id) ON DELETE RESTRICT,
    date_of_birth DATE NOT NULL,
    joining_date DATE NOT NULL,
    gender VARCHAR(20) NOT NULL,
    member_type VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_exited BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 8. Events Table
CREATE TABLE IF NOT EXISTS events (
    event_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_name VARCHAR(200) NOT NULL,
    event_type_id UUID NOT NULL REFERENCES event_types(event_type_id) ON DELETE RESTRICT,
    event_date DATE NOT NULL,
    created_by UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    description VARCHAR(1000) NOT NULL,
    status VARCHAR(30) NOT NULL,
    base_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 9. Event Participants Table
CREATE TABLE IF NOT EXISTS event_participants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_id UUID NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    member_id UUID NOT NULL REFERENCES members(member_id) ON DELETE RESTRICT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL,
    CONSTRAINT uq_event_participants UNIQUE (event_id, member_id)
);

-- 10. Contributions Table
CREATE TABLE IF NOT EXISTS contributions (
    contribution_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_id UUID NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    member_id UUID NOT NULL REFERENCES members(member_id) ON DELETE RESTRICT,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    payment_status VARCHAR(20) NOT NULL,
    payment_date TIMESTAMPTZ NULL,
    payment_mode VARCHAR(20) NOT NULL,
    cash_amount NUMERIC(12,2) NULL,
    upi_amount NUMERIC(12,2) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL,
    CONSTRAINT uq_contributions UNIQUE (event_id, member_id)
);

-- 11. Role Rights Table
CREATE TABLE IF NOT EXISTS role_rights (
    role_right_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    role VARCHAR(50) NOT NULL,
    module VARCHAR(100) NOT NULL,
    sub_module VARCHAR(100) NOT NULL,
    page VARCHAR(100) NOT NULL,
    access VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL,
    CONSTRAINT uq_role_rights UNIQUE (role, module, sub_module, page)
);

-- 12. Expenses Table
CREATE TABLE IF NOT EXISTS expenses (
    expense_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    expense_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL,
    submitted_by VARCHAR(150) NOT NULL,
    approved_by VARCHAR(150) NULL,
    description VARCHAR(1000) NOT NULL,
    file_name TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 13. Support Tickets Table
CREATE TABLE IF NOT EXISTS support_tickets (
    ticket_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ticket_no VARCHAR(50) NOT NULL UNIQUE,
    member_name VARCHAR(150) NOT NULL,
    member_id VARCHAR(100) NULL,
    related_event VARCHAR(200) NULL,
    ticket_type VARCHAR(100) NOT NULL,
    subject VARCHAR(300) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    status VARCHAR(50) NOT NULL,
    priority VARCHAR(50) NOT NULL,
    assigned_to VARCHAR(150) NULL,
    ref_no VARCHAR(100) NULL,
    utr VARCHAR(100) NULL,
    attachment TEXT NULL,
    resolution_notes VARCHAR(2000) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 14. System Settings Table
CREATE TABLE IF NOT EXISTS system_settings (
    setting_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT NOT NULL,
    category VARCHAR(100) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 15. Payment Transactions Table
CREATE TABLE IF NOT EXISTS payment_transactions (
    transaction_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    txn_number VARCHAR(50) NOT NULL UNIQUE,
    member_name VARCHAR(150) NOT NULL,
    event_name VARCHAR(200) NOT NULL,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    payment_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payment_mode VARCHAR(50) NOT NULL,
    utr VARCHAR(100) NULL,
    status VARCHAR(50) NOT NULL,
    verified_by VARCHAR(150) NULL,
    verified_on TIMESTAMPTZ NULL,
    notes VARCHAR(1000) NULL,
    screenshot TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 16. Gallery Photos Table
CREATE TABLE IF NOT EXISTS gallery_photos (
    photo_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(200) NOT NULL,
    event_name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    image_url TEXT NOT NULL,
    taken_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(1000) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 17. Budget Calculations Table
CREATE TABLE IF NOT EXISTS budget_calculations (
    budget_calculation_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    expense_item VARCHAR(150) NOT NULL,
    rate NUMERIC(12,2) NOT NULL DEFAULT 0,
    category VARCHAR(100) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 18. Ticket Types Table
CREATE TABLE IF NOT EXISTS ticket_types (
    ticket_type_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    type_name VARCHAR(150) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 19. Statuses Table
CREATE TABLE IF NOT EXISTS statuses (
    status_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    status_name VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- 20. Work Types Table
CREATE TABLE IF NOT EXISTS work_types (
    work_type_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    work_type_name VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_by VARCHAR(150) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(150) NULL,
    modified_on TIMESTAMPTZ NULL
);

-- ============================================================================
-- 2. SCHEMA UPGRADES (ALTER TABLE IF EXISTS ... ADD COLUMN IF NOT EXISTS)
-- ============================================================================

-- Roles
ALTER TABLE IF EXISTS roles ADD COLUMN IF NOT EXISTS default_contribution_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS roles ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS roles ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS roles ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS roles ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS roles ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS roles ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Event Types
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS base_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS has_tenure_rule BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS tenure_threshold_years NUMERIC(4,2) NOT NULL DEFAULT 1.0;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS new_entrant_share_percentage NUMERIC(5,2) NOT NULL DEFAULT 50.0;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS standard_share_percentage NUMERIC(5,2) NOT NULL DEFAULT 100.0;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS rule_description VARCHAR(200) NULL;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Users
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS profile_image VARCHAR(500) NULL;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS password_reset_otp VARCHAR(10) NULL;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS password_reset_otp_expiry TIMESTAMPTZ NULL;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS is_two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Members
ALTER TABLE IF EXISTS members ADD COLUMN IF NOT EXISTS member_type VARCHAR(20) NOT NULL;
ALTER TABLE IF EXISTS members ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS members ADD COLUMN IF NOT EXISTS is_exited BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS members ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS members ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS members ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS members ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS members ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS members ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Event Types
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS has_tenure_rule BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS tenure_threshold_years NUMERIC(4,2) NOT NULL DEFAULT 1.0;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS new_entrant_share_percentage NUMERIC(5,2) NOT NULL DEFAULT 50.0;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS standard_share_percentage NUMERIC(5,2) NOT NULL DEFAULT 100.0;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS rule_description VARCHAR(200) NULL;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS event_types ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Events
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS base_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS events ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Event Participants
ALTER TABLE IF EXISTS event_participants ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS event_participants ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS event_participants ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS event_participants ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS event_participants ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS event_participants ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS event_participants ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Contributions
ALTER TABLE IF EXISTS contributions ADD COLUMN IF NOT EXISTS cash_amount NUMERIC(12,2) NULL;
ALTER TABLE IF EXISTS contributions ADD COLUMN IF NOT EXISTS upi_amount NUMERIC(12,2) NULL;
ALTER TABLE IF EXISTS contributions ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS contributions ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS contributions ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS contributions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS contributions ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS contributions ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS contributions ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Role Rights
ALTER TABLE IF EXISTS role_rights ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS role_rights ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS role_rights ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS role_rights ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS role_rights ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS role_rights ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS role_rights ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Expenses
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Support Tickets
ALTER TABLE IF EXISTS support_tickets ADD COLUMN IF NOT EXISTS attachment TEXT NULL;
ALTER TABLE IF EXISTS support_tickets ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS support_tickets ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS support_tickets ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS support_tickets ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS support_tickets ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS support_tickets ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS support_tickets ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;
ALTER TABLE IF EXISTS support_tickets ALTER COLUMN attachment TYPE TEXT;

-- System Settings
ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS system_settings ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Payment Transactions
ALTER TABLE IF EXISTS payment_transactions ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS payment_transactions ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS payment_transactions ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS payment_transactions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS payment_transactions ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS payment_transactions ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS payment_transactions ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;
ALTER TABLE IF EXISTS payment_transactions ALTER COLUMN screenshot TYPE TEXT;

-- Gallery Photos
ALTER TABLE IF EXISTS gallery_photos ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS gallery_photos ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS gallery_photos ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS gallery_photos ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS gallery_photos ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS gallery_photos ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS gallery_photos ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;
ALTER TABLE IF EXISTS gallery_photos ALTER COLUMN image_url TYPE TEXT;

-- Budget Calculations
ALTER TABLE IF EXISTS budget_calculations ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS budget_calculations ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS budget_calculations ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS budget_calculations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS budget_calculations ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS budget_calculations ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS budget_calculations ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Ticket Types
ALTER TABLE IF EXISTS ticket_types ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS ticket_types ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS ticket_types ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS ticket_types ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS ticket_types ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS ticket_types ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS ticket_types ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;
ALTER TABLE IF EXISTS ticket_types DROP COLUMN IF EXISTS description;

-- Statuses
ALTER TABLE IF EXISTS statuses ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS statuses ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS statuses ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS statuses ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS statuses ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS statuses ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS statuses ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Work Types
ALTER TABLE IF EXISTS work_types ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS work_types ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS work_types ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS work_types ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS work_types ADD COLUMN IF NOT EXISTS created_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS work_types ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS work_types ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Device Details
ALTER TABLE IF EXISTS device_details ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS device_details ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS device_details ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS device_details ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- Device Login History
ALTER TABLE IF EXISTS device_login_history ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS device_login_history ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS device_login_history ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS device_login_history ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS device_login_history ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- User MFA Devices
ALTER TABLE IF EXISTS user_mfa_devices ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE IF EXISTS user_mfa_devices ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS user_mfa_devices ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS user_mfa_devices ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS user_mfa_devices ADD COLUMN IF NOT EXISTS modified_by VARCHAR(150) NULL;
ALTER TABLE IF EXISTS user_mfa_devices ADD COLUMN IF NOT EXISTS modified_on TIMESTAMPTZ NULL;

-- ============================================================================
-- 3. INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS ix_members_role_active ON members(role_id, is_active);
CREATE INDEX IF NOT EXISTS ix_events_date_type ON events(event_date, event_type_id);
CREATE INDEX IF NOT EXISTS ix_contributions_event_status ON contributions(event_id, payment_status);
CREATE INDEX IF NOT EXISTS ix_expenses_date_status ON expenses(expense_date, status);
CREATE INDEX IF NOT EXISTS ix_support_tickets_status_priority ON support_tickets(status, priority);
CREATE INDEX IF NOT EXISTS ix_payment_transactions_date_status ON payment_transactions(payment_date, status);
CREATE INDEX IF NOT EXISTS ix_gallery_photos_event_category ON gallery_photos(event_name, category);
CREATE INDEX IF NOT EXISTS ix_budget_calculations_expense_item ON budget_calculations(expense_item);
CREATE UNIQUE INDEX IF NOT EXISTS ix_role_rights_role_module_sub_module_page ON role_rights(role, module, sub_module, page);
